from .exceptions import Auth0Error

__all__ = ['Auth0Error']
